import React from 'react';
import { FileCheck, Scale, CheckCircle2, ShieldAlert } from 'lucide-react';

export const TermsPage: React.FC = () => {
  return (
    <div style={{ maxWidth: '900px', margin: '0 auto', padding: '3rem 1.5rem', display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      <div>
        <div className="hm-badge hm-badge-emerald" style={{ marginBottom: '0.5rem', gap: '0.3rem' }}>
          <FileCheck size={14} /> Usage Terms
        </div>
        <h1 style={{ fontSize: '2.5rem', fontWeight: 800 }}>Terms of Service</h1>
        <p style={{ color: 'var(--text-secondary)', marginTop: '0.5rem', fontSize: '1.05rem', lineHeight: 1.6 }}>
          Terms and conditions governing your use of the HireMind AI Interview Simulator platform.
        </p>
      </div>

      <div className="hm-card hm-card-emerald-glow" style={{ padding: '2rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1rem' }}>
          <Scale size={24} color="var(--primary)" />
          <h2 style={{ fontSize: '1.35rem', fontWeight: 700 }}>Educational & Portfolio Purpose</h2>
        </div>
        <p style={{ color: 'var(--text-main)', lineHeight: 1.65, fontSize: '0.98rem' }}>
          HireMind is an advanced AI interview practice platform created for software engineering candidates, college students, and job seekers to hone their technical and HR interview skills.
        </p>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
        <div className="hm-card">
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '0.5rem', color: 'var(--primary)' }}>1. Acceptable Use</h3>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.92rem', lineHeight: 1.6 }}>
            Users agree to use HireMind for legitimate interview practice, skill assessment, and educational self-improvement. Reverse-engineering system API keys or attempting automated abuse of LLM endpoints is strictly prohibited.
          </p>
        </div>

        <div className="hm-card">
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '0.5rem', color: 'var(--primary)' }}>2. AI Evaluation Disclaimer</h3>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.92rem', lineHeight: 1.6 }}>
            Interview scores, technical feedback, and hiring recommendations generated by HireMind are produced using AI models (Google Gemini) for guidance and preparation purposes. They do not guarantee employment decisions by third-party companies.
          </p>
        </div>

        <div className="hm-card">
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '0.5rem', color: 'var(--primary)' }}>3. Intellectual Property</h3>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.92rem', lineHeight: 1.6 }}>
            HireMind's design system, source code, and custom interviewer personas belong to the project author. Users retain full ownership of their original submitted code and uploaded resumes.
          </p>
        </div>
      </div>
    </div>
  );
};
